//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnclaimedFundsViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FindersList
    {
        public int ID { get; set; }
        public string HolderID { get; set; }
        public string HolderName { get; set; }
        public string ReportYear { get; set; }
        public string PropertyID { get; set; }
        public string OwnerName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string HolderAccountNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PropertyDescription { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
    }
}
